name: CI

on:
  push:
    branches: [ actions ]
  pull_request:
    branches: [ actions ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
#    - name: Test
#      run: dotnet test --no-restore --verbosity normal
    - name: Package
      run: dotnet pack --configuration Release -o nupkg
      working-directory: ./src/ZyRabbit
       
    - name: Publish nuget package
      run: |
        export NAME="$(find . -name '*.nupkg' -type f -exec basename {} ';')"
        echo "nuget package is $NAME"
        echo "::set-env name=PACKAGE::$NAME"
        '.\\$NAME' | xargs -0 -I pkg dotnet nuget push pkg -k $nuget_api_key -s "https://apiint.nugettest.org/v3/index.json" --skip-duplicate
      env:
        nuget_api_key: ${{ secrets.INTEGRATION_NUGET_TOKEN }}
      working-directory: ./src/ZyRabbit/nupkg
      continue-on-error: true
      
    - uses: actions/upload-artifact@v2
      name: Upload artifact
      with:
        name: "${{ env.PACKAGE }}"
        path: ./src/ZyRabbit/nupkg/*.nupkg