name: CI

on:
  push:
    branches: [ actions ]
  pull_request:
    branches: [ actions ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    
    - name: Set project
      run: |
      export PROJECTPATH="./src/ZyRabbit/ZyRabbit.csproj"
      echo "::set-env name=PROJECTPATH::$PROJECTPATH"
    
    - name: Set icon
      run: |
      DIR=$(dirname "${PROJECTPATH}")
      DIR=DIR + "/icon.png"
      cp "./icon.png" DIR
      
    - name: Restore
      run: dotnet restore "$PROJECTPATH"
    
    - name: Build
      run: dotnet build "$PROJECTPATH" --configuration Release --no-restore

#    - name: Test
#      run: dotnet test "$PROJECTPATH" --no-restore --verbosity normal
          
    - name: publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: $PROJECTPATH
        
        # NuGet package id, used for version detection & defaults to project name
        # PACKAGE_NAME: Core
        
        # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
        # VERSION_FILE_PATH: Directory.Build.props

        # Regex pattern to extract version info in a capturing group
        VERSION_REGEX: <VersionPrefix>(.*)<\/VersionPrefix>
        
        # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
        # VERSION_STATIC: 1.0.0

        # Flag to toggle git tagging, enabled by default
        TAG_COMMIT: true

        # Format of the git tag, [*] gets replaced with actual version
        TAG_FORMAT: v*

        # API key to authenticate with NuGet server
        NUGET_KEY: ${{secrets.INTEGRATION_NUGET_TOKEN}}

        # NuGet server uri hosting the packages, defaults to https://api.nuget.org
        NUGET_SOURCE: https://apiint.nugettest.org

        # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
        # INCLUDE_SYMBOLS: false
      
    - uses: actions/upload-artifact@v2
      name: Upload artifact
      with:
        name: "${{ env.PACKAGE }}"
        path: ./src/ZyRabbit/nupkg/*.nupkg